### ISSUE TITLE
Provide informative errors for callback functions

### ISSUE THREAD

**Issue by yeesian** [JuliaOpt/KNITRO.jl#1]
based on the error codes `KTR_RC_CALLBACK_ERR`, `KTR_RC_EVAL_ERR`, and `KTR_RC_USER_TERMINATION` 

> Callbacks should return 0 if successful, a negative error code if not.
> Possible unsuccessful (negative) error codes for the func/grad/hess
> callback functions include:
> 
>   KTR_RC_CALLBACK_ERR       (for generic callback errors)
>   KTR_RC_EVAL_ERR           (for evaluation errors, e.g log(-1))
> 
> In addition, for the "func", "newpoint", "ms_process" and "mip_node"
> callbacks, the user may set the following return code to force KNITRO
> to terminate based on some user-defined condition.
> 
>   KTR_RC_USER_TERMINATION   (to use a callback routine for user
>   specified termination)

**Comment by sylvainmouret** [comment]
Can you explain what the problem is exactly?
Or can we close this issue?

**Comment by yeesian** [comment]
I was originally thinking of more readable `Symbols` in julia, rather than integers for error codes, but I haven't yet seen this actually being an issue for users, so let's close this issue for now. We can always open a new issue if need be.
