### ISSUE TITLE
Optimizer not defined

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/KNITRO.jl#107]
Strictly speaking this error should not occur - any way to find out why?

```
(jump-dev) pkg> st
    Status `~/Documents/jump-dev/Project.toml`
  [07493b3f] Alpine v0.1.5+ [`~/.julia/dev/Alpine`]
  [60bf3e95] GLPK v0.9.1
  [b6b21f68] Ipopt v0.5.4
  [4076af6c] JuMP v0.19.0
  [2ddba703] Juniper v0.2.5+ [`~/.julia/dev/Juniper`]
  [67920dd8] KNITRO v0.6.0
  [b8f27783] MathOptInterface v0.8.4+ [`~/.julia/dev/MathOptInterface`]
  [de0858da] Printf 

julia> using KNITRO, JuMP, MathOptInterface
[ Info: Recompiling stale cache file /Users/kaarthik/.julia/compiled/v1.1/KNITRO/9GHjY.ji for KNITRO [67920dd8-b58e-52a8-8622-53c4cffbe346]

julia> m = JuMP.direct_model(KNITRO.Optimizer())
ERROR: UndefVarError: Optimizer not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
```

**Comment by kaarthiksundar** [comment]
resolved.

**Comment by frapac** [comment]
I just provide an answer for those encountering a similar issue: Knitro supports MathOptInterface only for version >= `11.0` (see [README.md](https://github.com/JuliaOpt/KNITRO.jl#mathoptinterface-interface)). The latest version of Knitro adds support for incremental changes in the optimization model, and a lot of other stuffs. We highly recommend to upgrade to the latest Knitro version, if compatibility is not an issue.
