### ISSUE TITLE
migration to jump-dev

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/KNITRO.jl#162]
@frapac, we're moving repositories out of the JuliaOpt org. Would Artelys prefer to move this repository into [jump-dev](https://github.com/jump-dev) or a more official "Artelys" organization?

**Comment by frapac** [comment]
I do not see any objection in moving this repo into jump-dev

**Comment by mgabay** [comment]
Hi Miles and François,
I support moving it to jump-dev. You both, Yeesian and the community have been doing tremendous work around this interface and I see no reason to sever this link.

**Comment by mlubin** [comment]
Got it, thanks!
