### ISSUE TITLE
fallback options for MPB interface

### ISSUE THREAD

**Issue by yeesian** [JuliaOpt/KNITRO.jl#18]
I'm getting
```
ERROR: `isobjlinear` has no method matching isobjlinear(::QCQP)
 in loadnonlinearproblem! at /Users/yeesian/.julia/v0.3/KNITRO/src/KnitroSolverInterface.jl:122
 in convexnlptest at /Users/yeesian/.julia/v0.3/MathProgBase/test/nlp.jl:178
```
The actual test is as follows:
```julia

type QCQP <: MathProgSolverInterface.AbstractNLPEvaluator
end

# [...]

function convexnlptest(solver=MathProgBase.defaultNLPsolver)

    m = MathProgSolverInterface.model(solver)
    l = [-2,-2]
    u = [2,2]
    lb = [-Inf]
    ub = [1.0]
    MathProgSolverInterface.loadnonlinearproblem!(m, 2, 1, l, u, lb, ub, :Min, QCQP())

    MathProgSolverInterface.optimize!(m)
    stat = MathProgSolverInterface.status(m)

    @test stat == :Optimal
    x = MathProgSolverInterface.getsolution(m)
    @test_approx_eq_eps (x[1]+x[2]) -1/3 1e-3
    @test_approx_eq_eps MathProgSolverInterface.getobjval(m) -1-4/sqrt(3) 1e-5

end
```
Should I be assuming that `d::AbstractNLPEvaluator` will always provide
```
isobjlinear(d::AbstractNLPEvaluator)
isobjquadratic(d::AbstractNLPEvaluator)
isconstrlinear(d::AbstractNLPEvaluator, i)
```
or do I provide fallback options in the event that it doesn't?

Related: #17

**Comment by yeesian** [comment]
It's non-urgent, but I'm just wondering if it is non-trivial to get this implemented? I don't mind giving it a shot (as an exercise in getting to know the codebase better), but I'm not sure what needs to be done, apart from appending
```julia
isobjlinear
isobjquadratic
isconstrlinear
```
to the list of exported functions in the relevant [solver interfaces](https://github.com/yeesian/MathProgBase.jl/tree/master/src/SolverInterface). I see that the implementation ([for nlp](https://github.com/JuliaOpt/JuMP.jl/blob/0b7cf203039aaf0d444f990efcf8ea58e4d65d08/src/nlp.jl#L359-L363)) is done in JuMP, but am unsure about everything else.

**Comment by mlubin** [comment]
Just add
```
isobjlinear(::AbstractNLPEvaluator) = false
...
```
to ``SolverInterface/nonlinear.jl``.

**Comment by yeesian** [comment]
closed via https://github.com/JuliaOpt/MathProgBase.jl/pull/53
