### ISSUE TITLE
Expose ZLM context

### ISSUE THREAD

**Issue by yeesian** [JuliaOpt/KNITRO.jl#2]
For creating and destroying solvers in high volume:

> High volume applications construct new KNITRO instances repeatedly,
> each lasting only a short time.  Special functions allow a single
> license to be checked out once for a sequence of KNITRO instances.
> Reusing a license saves time in the KNITRO solver, and improves the
> performance of the Ziena License Manager server.
> 
> The typical calling sequence is:
>    ZLM_checkout_license
>      KTR_new_zlm
>        KTR_init_problem
>        KTR_solve (a single call, or a reverse communications loop)
>      KTR_free
>      KTR_new_zlm
>        KTR_init_problem
>        KTR_solve (a single call, or a reverse communications loop)
>      KTR_free
>      ...
>    ZLM_release_license
> 
>  High volume functions are not available in the "student" version.

**Comment by frapac** [comment]
This is adressed for KNITRO 11.x in #94
