### ISSUE TITLE
ReverseDiffSparse getindex error

### ISSUE THREAD

**Issue by lauren897** [JuliaOpt/KNITRO.jl#23]
When running

`status = solve(mod)`

I get this error:

```
ERROR: `getindex` has no method matching getindex(::Int64, ::JuMPArray##8490{Variable}, ::Int64, ::Int64)
 in sparsity_gen at /Users/laurenberk/.julia/v0.3/ReverseDiffSparse/src/hessian.jl:93
 in anonymous at no file:29
 in gen_hessian_sparse_color_parametric at /Users/laurenberk/.julia/v0.3/ReverseDiffSparse/src/coloring.jl:300
 in prep_sparse_hessians at /Users/laurenberk/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:107
 in initialize at /Users/laurenberk/.julia/v0.3/JuMP/src/nlp.jl:83
 in loadnonlinearproblem! at /Users/laurenberk/.julia/v0.3/KNITRO/src/KnitroSolverInterface.jl:73
 in solvenlp at /Users/laurenberk/.julia/v0.3/JuMP/src/nlp.jl:463
 in solve at /Users/laurenberk/.julia/v0.3/JuMP/src/solvers.jl:6
```

The model formulation works fine in Gurobi, I've set starting values for all my variables, and I'm using @addNLConstraint and setNLObjective everywhere.  I can send the model itself if that's helpful.

**Comment by mlubin** [comment]
This unfriendly error looks like it means that there's a variable being used as an index somewhere in the model. Please post or send me the model.

**Comment by lauren897** [comment]
Hm.  The model's below.  I can't find any clashing names, though I have definitely been guilty of that before.  I think I have:

Model vars: x, x2, xreal, z
iterators: i, j, k, m, p1, p2
constants: n, K, p, L, y
(and yes, writing that out makes me feel somewhat ashamed of my lack of any sort of naming conventions... but the sets do seem to be disjoint)

Stuff that runs before the model:

```
using JuMP, Gurobi, KNITRO

n = 10 #dimensions
K = 5 #sparsity
p = 11 #precision
L = 10 #granularity of steps

Sigma = [
[0.15 	0.058 	0.057 	0.057 	0.014 	0.005 0 0 0 0], 
[.058 	.133 	.086 	.057 	.049 	-.043 0 0 0 0], 
[.057 	.086 	.127 	.058 	.031 	-0.024 0 0 0 0], 
[.057 	.057 	.058 	.413 	-.263 	0 0 0 0 0], 
[.014 	.049 	.031 	-.263 	.421 	-.075 0 0 0 0], 
[.005 	-.043 	-.024 	0 		-.075 	.2 0 0 0 0], 
[0 0 0 0 0 0 .1 0 0 0], 
[0 0 0 0 0 0 0 .1 0 0], 
[0 0 0 0 0 0 0 0 .1 0], 
[0 0 0 0 0 0 0 0 0 .1]]
lambda = eig(Sigma)[1]
U = eig(Sigma)[2] #columns are eigenvectors


#Design H_k function
function Hk(list, sparsity)
	order = sortperm(-abs(vec(list))) #1 gives highest magnitude, n lowest
	norm = 0
	for i = 1:sparsity
		norm += list[order[i]]^2
	end
	norm = norm^(0.5)
	ksparse = zeros(length(list))
	for i = 1:sparsity
		ksparse[order[i]] = list[order[i]]/norm
	end
	return ksparse
end

# Random initialization
beta0 = rand(n)
beta0 = beta0 / norm(beta0)
beta0 = Hk(beta0, K)

#Iterate
beta = beta0
for i=1:100
	beta = Hk(beta + (2/L)*Sigma*beta, K)
	#println((transpose(beta)*Sigma*beta)[1])
end
	println(beta)
	println(transpose(beta0)*Sigma*beta0)
	println(transpose(beta)*Sigma*beta)
	println(transpose(beta)*beta)

#Optimize over fixed support
y=zeros(n)
for i=1:n
	if(abs(beta[i])>0)
		y[i]=1
	end
end
println("y=",y)
```

The model:
```
#using Base.Test

mod = Model(solver=KnitroSolver())

#Try VarBranch=3, strong branching

@defVar(mod, -1<=x[1:n]<=1) #coefficients of eigenvectors
@defVar(mod, 0<=x2[1:n]<=1) #coefficients squared
@defVar(mod, -1<=xreal[1:n]<=1) #components in Rn
@defVar(mod, z[1:n,1:p,1:p], Bin) #binary expansion of x

for j=1:n
	setValue(x[j], 0)
	setValue(x2[j], 0)
	setValue(xreal[j], 0)
	for p1=1:p
		for p2=1:p
			setValue(z[j,p1,p2], 0)
		end
	end
	setValue(z[j,2,2], 1)
end

for j=1:n
	for k=1:p
		for m=1:p
			@addNLConstraint(mod, z[j,k,m] <= z[j,k,k]) 
			@addNLConstraint(mod, z[j,k,m] <= z[j,m,m])
			@addNLConstraint(mod, z[j,k,m] >= z[j,k,k]+z[j,m,m]-1)
		end
	end
	@addNLConstraint(mod, x[j] == sum{(2.0^(-k+2))*z[j,k,k],k=1:p}-1)
	@addNLConstraint(mod, x2[j] == sum{(2.0^(-k-m+4))*z[j,k,m],k=1:p,m=1:p}-2*x[j]-1)
end

for i=1:n
	@addNLConstraint(mod, xreal[i] == sum{U[i,j]*x[j],j=1:n})
	@addNLConstraint(mod,  xreal[i] >=-y[i])
	@addNLConstraint(mod,  xreal[i] <=y[i])
end


@addNLConstraint(mod, sum(x2)<=1)

@setNLObjective(mod, Max, sum{lambda[j]*x2[j],j=1:n})
status = solve(mod)
```

**Comment by mlubin** [comment]
This could potentially be a bug, but I'm traveling and don't have time to look into it right now.
Which of the constraints present are actually nonlinear? Try using ``@addConstraint`` instead for the linear constraints, though if you want to use KNITRO you currently need to have a nonlinear objective or at one nonlinear constraint.

**Comment by lauren897** [comment]
That would do it - I don't actually have nonlinear constraints or objective - it's just a linear MIP.  I was originally getting a different error with just @addConstraint, and Yee Sian said I should try changing them all to say NL even if they were linear, which resulted in the new error above.  I was running into some weird precision issues with Gurobi and it sounded like KNITRO might have a leg up on some MIP problems.  There are other formulations that are truly nonlinear that I will give a shot later.  Or I might artificially add a non-binding constraint and see what that does.

**Comment by joehuchette** [comment]
Is this a problem with KNITRO the solver or KNITRO.jl? Seems like there should at least be a useful error message if no nonlinearities are present.

**Comment by mlubin** [comment]
KNITRO.jl doesn't implement ``loadproblem!``.

**Comment by yeesian** [comment]
Yeah, it's a problem with `KNITRO.jl` (and not the solver), since KNITRO doesn't yet implement `loadproblem!`, I will include a warning in the documentation after I get back

**Comment by mlubin** [comment]
Fixed the bug that caused the ``getindex`` error, thanks for reporting!

The model you posed will now run (after ``Pkg.update()``) if you change the last constraint to
```
@addConstraint(mod, sum(x2)<=1)
```
because ``sum()`` can't be used in nonlinear constraints.
