### ISSUE TITLE
Documentation for key functions

### ISSUE THREAD

**Issue by cdagnino** [JuliaOpt/KNITRO.jl#25]
Hi,

Could you provide some syntax and explanation for a few key functions?
In particular, I'm confused about `initializeProblem()`
For example, how would I initialize a problem without passing the analytic gradient nor the hessian? Or passing just the gradient but not the hessian?
Can I avoid passing the sparsity patterns?
Since this should be consistent with the `setCallbacks()` function, I'm guessing some help on that function would help too.

Thanks!

**Comment by yeesian** [comment]
Hi @cdagnino, you should have a look at the [JuMP.jl](https://github.com/JuliaOpt/JuMP.jl) package which allows you to do just that (:

Here's an example of something you might do with KNITRO.jl ([callback functions, sparsity patterns, and all](https://github.com/JuliaOpt/KNITRO.jl/blob/master/examples/minlp.jl)), and how you might do it through JuMP.jl ([without having to specify the gradient/hessian/etc](https://github.com/JuliaOpt/KNITRO.jl/blob/master/examples/jump_minlp.jl)). You can check out other examples in [this folder](https://github.com/JuliaOpt/KNITRO.jl/tree/master/examples) to have a sense of how you can model different kinds of problems.

Since this came up on a few occasions, may I check

1. Which parts of the documentation have you been referencing?
2. How might we be able to better direct people to modelling packages such as JuMP?

**Comment by cdagnino** [comment]
@yeesian : thanks for your answer. I've used JuMP and did see the JuMP examples, but it seems the problems I tackle are not easily converted into JuMP algebra (I've recently posted on julia-opt google groups asking for a simple way to convert a function).

1. I read http://knitrojl.readthedocs.org/solving.html  and  http://knitrojl.readthedocs.org/example.html but still had many questions. IMHO, I think it would benefit users to have some reference on the key functions I mentioned above. Otherwise, a more annotated example (and one without providing the hessian for example) would also help a lot. I understand that for someone used to interfacing KNITRO, for example, from C, will find many of these functions easy to use, but that might not be the case for many users.

2. I think the JuMP examples are great and easy to understand. The Docs definitely direct people to JuMP. My problem is that the objective functions I'm using are not trivial to port to JuMP (they might have a lot of algebra, an integral inside, etc.). The workflow I'm using is to define the functions, test them and attempt to optimize them with Optim at first to later move to solvers such as KNITRO.

**Comment by yeesian** [comment]
May I check: were you previously using KNITRO's MATLAB API?

**Comment by cdagnino** [comment]
The examples definitely help! But, to refer to my particular problem, I didn't find one that didn't provide the full hessian and hessian structure and sometimes providing that becomes difficult for large problems.

I have used the Matlab API, but I'm very far from an expert in it. However, I did find [this doc page](https://www.artelys.com/tools/knitro_doc/3_referenceManual/knitromatlabReference.html) very helpful.

If your API closely resembles the C one, then an option for some features is just to point to the official KNITRO documentation and explicitly say that your API works the same way. I do think your users with limited C/KNITRO exposure would benefit from writing your own docs.

Is there a MathProgBase fallback you recommend when JuMP is not an option? I'm going through [this page](https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/nlp.jl) and it seems very similar to the way the KNITRO.jl examples are built.

On a more general level, it is my understanding that the Julia-opt spirit is to have a single API and then attach different solvers. JuMP does this beautifully and IMHO is decently documented in the specific solver docs. When this is not an option, I could gather from the docs that MathProgBase acts as the common API, but I think this is not completely clear (if you find merit in this, I could post an issue on MathProgBase or something like that) 

Thanks once again! If I do eventually learn this stuff, I'd be happy to help write up some doc pages.

**Comment by yeesian** [comment]
That clarifies alot, thanks!

[It can be done](https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/ktr_functions.jl#L374-L400), but we haven't yet provided a convenient way to [initialize the problem](https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/KNITRO.jl#L88-L96) without specifying the hessian in this package.

While your interest is piqued, might you be interested to implement this function, by providing a version of `initializeProblem` that doesn't require the hessian to be specified? We'll help guide you along where we can. Here's the way this package is structured:

- **[C-facing interface]**: `src/ktr_functions.jl` (which calls the KNITRO library through their C interface, so you'll see functions like `init_problem`)
- **[Intermediate Julia interface]**: `src/KNITRO.jl` (where `initializeProblem`, `setCallbacks`, etc are defined)
- (optional reading) **[MathProgbase interface]**: `src/KnitroSolverInterface.jl` (which implements [solver-independent interfaces](http://mathprogbasejl.readthedocs.org/en/latest/index.html))

**Comment by mlubin** [comment]
@cdagnino, we do encourage use of the MathProgBase interface over the low-level knitro interface. There shouldn't be a reason to tie your code to a particular commercial solver, and knitro provides no support for the development of the julia-knitro interface. If it's not clear how to do something through the MPB interface, please do open an issue or ask on julia-opt. There may be pieces that are not fully developed because nobody has needed them up to this point.

**Comment by yeesian** [comment]
@mlubin I think he's looking for a blackbox nonlinear interface that doesn't require you to specify the hessian. Does the MPB interface allow for that yet? And do we have solvers that allow him to do so?

**Comment by mlubin** [comment]
http://mathprogbasejl.readthedocs.org/en/latest/nlp.html#features_available
MPB allows for it, just don't include ``:Grad``, ``:Jac``, or ``:Hess`` in the list of features supported by the problem. The knitro interface should check ``features_available`` and call the corresponding knitro functions. Knitro doesn't need first or second derivatives (but of course it will do much better if they are provided).

**Comment by yeesian** [comment]
Ah, I'll leave that as a second task for @cdagnino, if he's up for it (:

**Comment by cdagnino** [comment]
@mlubin : thanks for the answer. I'll look into it and post on Julia-opt if I fail. If I have the time I'll post an IJulia notebook for people as clueless as myself.

@yeesian : I can give it a try, but my coding skills may not be up to the par. Should I just keep questions piling up here or is there something like a gitter chat? I have quite a lot of questions that are not directly related to this issue.

**Comment by mlubin** [comment]
@cdagnino, also, feel free to contact Knitro support to let them know that you're interested in using Knitro in Julia. If enough people do this, then they're likely to eventually provide official support and implement the features which are missing.

**Comment by yeesian** [comment]
Sorry @cdagnino, I have been really busy the past few weeks -- we should take these conversations elsewhere. @mlubin, I didn't realize JuliaOpt has a [gitter chatroom](https://gitter.im/JuliaOpt); is it open to the public?

**Comment by rt5592** [comment]
> MPB allows for it, just don't include :Grad, :Jac, or :Hess in the list of features supported by the problem
to implement this:
function MathProgBase.initialize(d::AbstractNLPEvaluator, requested_features::Vector{Symbol})
    for feat in requested_features
        if !(feat in [ ])                                                 # empty array here ?
            error("Unsupported feature $feat")
            # TODO: implement Jac-vec and Hess-vec products
            # for solvers that need them
        end
    end
end

 MathProgBase.features_available(d::AbstractNLPEvaluator) = [ ]   # empty array here ?

is this true with other MPB solvers, such as Ipopt ?  
Thank you for clarifying

**Comment by sylvainmouret** [comment]
I don't know for Ipopt.
It depends on the solver's capability to handle problems for which no derivatives are provided.
(I suggest to post this comment on the corresponding Github repository, you'll probably get a better answer there).

**Comment by sylvainmouret** [comment]
@mlubin @yeesian I read this issue but I'm confused as to what would need to be done to close this issue. Can you enlighten me?

**Comment by mlubin** [comment]
Given that this issue is more than two years old, probably safe to close. It's a request for more examples for the pure knitro interface.

**Comment by rt5592** [comment]
thank you the reply @mlubin.
I didn't open a new issue because this one contains what I wanted to ask about already. But I will re-post it in 'MathProgBase'.

Thanks.
