### ISSUE TITLE
MathProgSolverInterface.optimize! cannot be called repeatedly

### ISSUE THREAD

**Issue by davidanthoff** [JuliaOpt/KNITRO.jl#30]
I'm trying to call the Knitro solver via the MathProgSolver interface repeatedly for a problem where the structure is not changed between solve calls, but parameters of the objective function might change their value. With Ipopt I can just call the ``MathProgSolverInterface.optimize!`` repeatedly for the same problem, and it will just resolve. With the Knitro package I get an error saying ``ERROR: KTR_init_problem has already been called``.

Would it be possible to change the Knitro implementation such that the KTR_init_problem call happens in one of the MathProgSolver init functions, and not in the actual call to solve? That way one could use Knitro via this interface for example in an inner loop that repeatedly optimizes a problem, but just for small changes in parameters.

Here is a [gist with repo code](https://gist.github.com/davidanthoff/81d6282581a82f8eb022). With Knitro you get the error, if one uses Ipopt instead (by swapping the comment on line 21 and 22) everything works.

My sense is that the MathProgBase interface should actually prescribe whether this is something solvers need to support. @mlubin, @tkelman.

**Comment by mlubin** [comment]
Sure, this should be supported. PRs would help more than prescriptions though :)

We would appreciate it if you let KNITRO support know that you find this wrapper useful. If enough people do so, we hope that official support will follow.

**Comment by davidanthoff** [comment]
#31. I have way too little knowledge of MathProgBase or Knitro to tell whether this is an ok way to enable this scenario... All the tests seem to pass, at least something.

**Comment by yeesian** [comment]
closed by #31
