### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaOpt/KNITRO.jl#32]
The current taged version has an error when one calls ``Pkg.test("KNTIRO")``. The master version works fine.

**Comment by yeesian** [comment]
:ok_hand: it's been awhile since the last time. I'm currently in new hampshire though, can you help?

**Comment by davidanthoff** [comment]
I don't have commit access. Couldn't the current master just be tagged as the next release? Not sure how I could help with that. @mlubin

**Comment by mlubin** [comment]
I'll tag

**Comment by davidanthoff** [comment]
Thanks!

**Comment by yeesian** [comment]
Thanks miles! And thanks for the reminder david!

Unrelatedly, I'm confused: is commit access needed to tag a package? I
thought the procedure was to tag the package in a julia session, and submit
a PR of the diff to METADATA.

**Comment by mlubin** [comment]
You need commit access to properly tag a release: https://github.com/JuliaOpt/KNITRO.jl/releases

**Comment by IainNZ** [comment]
Its because of the overloaded meaning of tag: the git notion of it, and the Julia notion. Only can get both simultaneously with package commit access.
