### ISSUE TITLE
KNITRO gives bad duals

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/KNITRO.jl#36]
Currently:
```
getreducedcosts(m::KnitroMathProgModel) = zeros(m.numVar)
getconstrduals(m::KnitroMathProgModel) = zeros(m.numConstr)
```
Can we return the actual lagrange multipliers instead? JuMP now has tests for nonlinear duals which KNITRO is failing.

**Comment by yeesian** [comment]
I think the lagrange multipliers are `m.inner.lambda`, but I'll check
