### ISSUE TITLE
Add support for new functionality in KNITRO 10

### ISSUE THREAD

**Issue by yeesian** [JuliaOpt/KNITRO.jl#40]
News: http://www.artelys.com/news/160/50/Artelys-presents-Knitro-10-0-at-the-INFORMS-Conference-in-Philadelphia

**Comment by frapac** [comment]
KNITRO.jl would support new KNITRO API with #94

**Comment by mgabay** [comment]
This news originally refered to the OO intefaces which address other programming languages but did not add specific features and new options act_qpalg, datacheck and out_csvinfo.

I think this can be closed thanks to recent works from François
