### ISSUE TITLE
Add support to work with Atom

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaOpt/KNITRO.jl#46]
I got this error when I want to use KNITRO in Atom. 

LoadError: error compiling loadproblem!: error compiling call: could not load library "libknitro".

**Comment by mlubin** [comment]
This is not directly related to Atom. Please make sure the proper environment variables are set so that julia can find "libknitro".

**Comment by Kelvyn88** [comment]
I declared the environment variable. From Julia knit is running well, but fails when I run the same code in atom

**Comment by mlubin** [comment]
@Kelvyn88, if Atom isn't picking up the environment variables, you can set them from inside julia before loading knitro, e.g.,
```
ENV["LD_LIBRARY_PATH"] = ...
using KNITRO
```

**Comment by molivo** [comment]
@mlubin I have the same issue. I tried adding `ENV["LD_LIBRARY_PATH"]` and `ENV["DYLD_LIBRARY_PATH"]` to the juliarc.jl file. That solves the problem in the console only, but the problem persists when I try to run a file from an open pane in Atom. Do you have any suggestions?

**Comment by ziminzeng** [comment]
I have the same issue too. Does anyone know how to solve the problem? Thanks a lot

**Comment by GillesBareilles** [comment]
@ziminzeng, could you give details on your configuration (OS, knitro version, atom install, ...), the context in which knitro fails, and the error returned by Julia please ?

Specifically, is there an environment variable pointing to the `lib` subdirectory of the Knitro install folder ?
