### ISSUE TITLE
Rootfinding problem

### ISSUE THREAD

**Issue by pierremabille** [JuliaOpt/KNITRO.jl#51]
Is there any other (simpler) way to set up and solve a rootfinding problem in the current Julia version of KNITRO than to write it as a minimization problem (in which the objective function is a constant and the equations whose roots we want to find are the constraints)? Thanks.

**Comment by mlubin** [comment]
Not sure how this relates to the Julia Knitro wrapper. Does Knitro have an interface for rootfinding that's not exposed here?

**Comment by pierremabille** [comment]
Well I'm looking for a Julia equivalent of the MATLAB command knitromatlab_fsolve, I didn't find a similar command.

**Comment by mlubin** [comment]
I don't believe there is such an interface. We'd certainly accept it as a contribution or you could contact Artelys and make them aware of your request.
