### ISSUE TITLE
Derivative-free (un)constrained nonlinear problem

### ISSUE THREAD

**Issue by pierremabille** [JuliaOpt/KNITRO.jl#52]
Hi, is there a way to solve an (un)constrained nonlinear problem with KNITRO.jl, without specifying the gradient, Jacobian and Hessian? The objective function is a generic function that has no simple analytic expression. I have been exploring the MathProgBase interface, mostly based on the examples here (https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/nlp.jl), but it looks like when we use KNITRO.jl we can only omit the Hessian (https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/KnitroSolverInterface.jl#L76). 
Thanks!

**Comment by mlubin** [comment]
I believe Knitro supports not providing derivatives, but that's not currently exposed through the MathProgBase interface. You'll have to look into the Knitro API and figure out how to do this, or ask Artelys.

**Comment by pierremabille** [comment]
I am also looking at how to do it in the knitro API, will post an example if I manage to do it, otherwise if someone has already done it, an example would be very helpful.

**Comment by mlubin** [comment]
You'll likely reach a bigger audience by posting on the [julia-opt](https://groups.google.com/forum/#!forum/julia-opt) list. As you can see above, very few people are subscribed to these issues.

**Comment by pierremabille** [comment]
Ok, I managed to do it, will post an example when I have time, possibly on JuliaOpt. 
Additional question: what do jac_con, jac_var, hess_row, hess_col correspond to in your examples?
Thanks!

**Comment by yeesian** [comment]
is this a dup of #55 ?

**Comment by pierremabille** [comment]
Yes. I eventually didn't use the MathProgBase interface, looks like it's easier to tweak the solver's parameters directly as I did in https://github.com/JuliaOpt/KNITRO.jl/issues/55.
