### ISSUE TITLE
Derivatives sparsity patterns

### ISSUE THREAD

**Issue by pierremabille** [JuliaOpt/KNITRO.jl#54]
Hi,
What do jac_con, jac_var, hess_row, hess_col correspond to in your examples, and how to set them if the objective function has no clear analytical form?
Thanks!

**Comment by mlubin** [comment]
You should look at the documentation in the Knitro API to see what to set these values to when you don't provide derivatives: https://www.artelys.com/tools/knitro_doc/3_referenceManual/callableLibrary/API.html
