### ISSUE TITLE
passing linearity

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/KNITRO.jl#62]
TODO: Revert https://github.com/JuliaOpt/KNITRO.jl/commit/ecabd477d20fe48773263751b5bc0fe625d54993 and bump our minimum required version to 10.1.2. See https://groups.google.com/d/msg/knitro/H9ck55HjY0s/0McW9ZEzEQAJ.

**Comment by GillesBareilles** [comment]
This was done at commit 67a6e8379d1b39476282abb56a6e65598e2896c6. The example from the google thread now gives the correct objective.
