### ISSUE TITLE
Package Tests are Brittle when using a License Server

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/KNITRO.jl#64]
When using a Knitro license server, from what I can tell, each call to KnitroSolver() checks out a new license.  Combine this with the license release timer and Pkg.test("KNITRO") quickly runs into "### License found, but all copies are checked out" errors. 

This may be related to #58.

**Comment by joaquimg** [comment]
Any news on this one?

**Comment by ccoffrin** [comment]
I have not had time to work on it.  But I hope to at some point.

**Comment by joaquimg** [comment]
once JuliaOpt/MathProgBase.jl#197 is merged this should be solved

**Comment by joaquimg** [comment]
Merged!
@ccoffrin could you test with your license server? 
Mine is working smoothly.

**Comment by ccoffrin** [comment]
@joaquimg master seems to be much better now, thanks!!!

All tests did not pass on my Julia 0.5 install, but that's probably because I am running old versions of something.

```
Test optimal solutions
3 facts verified.
...
ERROR: LoadError: LoadError: Unsupported feature Jac
 in initialize(::Rosenbrock, ::Array{Symbol,1}) at /Users/cjc/.julia/v0.5/MathProgBase/test/nlp.jl:272
 in loadproblem!(::KNITRO.KnitroMathProgModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::Rosenbrock) at /Users/cjc/.julia/v0.5/KNITRO/src/KnitroSolverInterface.jl:80
 in rosenbrocktest(::KNITRO.KnitroSolver) at /Users/cjc/.julia/v0.5/MathProgBase/test/nlp.jl:308
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
while loading /Users/cjc/.julia/v0.5/KNITRO/test/mathprogtest.jl, in expression starting on line 3
while loading /Users/cjc/.julia/v0.5/KNITRO/test/runtests.jl, in expression starting on line 2
```

**Comment by joaquimg** [comment]
Nice!
Indeed I did not solve that error, but that is not related to this issue anymore.

**Comment by mlubin** [comment]
The error should be fixed by https://github.com/JuliaOpt/KNITRO.jl/pull/73

**Comment by sylvainmouret** [comment]
Indeed it is important to free the Knitro context in order to release the license.
I just tested on Windows on my machine, and it works fine.
