### ISSUE TITLE
support for 0.6

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaOpt/KNITRO.jl#70]
Currently the tests are failing for the new version of julia. As a user of KNITRO, I will forward this to the folks at Artelys to ask for support. 

**UPDATE**
after asking KNITRO for help, they said that they do not (yet at least) support julia and since they are in the middle of a release they have other priorities at the moment. 

@yeesian do you think that you could take a look at this? I looked at it but could not figure it out. Thanks!

**Comment by sylvainmouret** [comment]
This issue has been fixed in #73
