### ISSUE TITLE
Pkg.test("KNITRO") LoadError

### ISSUE THREAD

**Issue by rt5592** [JuliaOpt/KNITRO.jl#76]
Hi
I added the "KNITRO" package; when I try to run a test (Pkg.test("KNITRO") ) I get the following error:

ERROR: LoadError: LoadError: LoadError: error compiling createProblem: error compiling Type: could not load library "knitro" the specified module could not be found.

Any insight is appreciated. Thanks.

**Comment by sylvainmouret** [comment]
Hi,
Just to make sure, have you downloaded the Artelys Knitro ditribution from [Artelys' website](http://www.artelys.com/knitro)?
The Julia package "KNITRO" is only the interface that allows solving models with Knitro, from Julia.
Best,

**Comment by rt5592** [comment]
Ok thanks.

**Comment by rt5592** [comment]
just to clarify, I have to have the Artelys Knitro distribution to use Knitro solver with MathProgBase and JuMP as well?

thanks!

**Comment by sylvainmouret** [comment]
Yes exactly.
You may download a trial license from the above website if you wish.
