### ISSUE TITLE
JuMP.Model(solver=NLopt.NLoptSolver()) fails with constraints

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaOpt/KNITRO.jl#78]
This works:

```
m = JuMP.Model(solver=NLopt.NLoptSolver(algorithm=algorithm)
@JuMP.variable(m, W[i=1:nm, j=1:nk] >= 0., start =initW[i, j])
```

however this fails:

```
m = JuMP.Model(solver=NLopt.NLoptSolver(algorithm=algorithm)
@JuMP.variable(m, W[i=1:nm, j=1:nk], start =initW[i, j])
@JuMP.constraint(m, W .>= 0.)
```

**Comment by sylvainmouret** [comment]
Hello,
This issue does not seem to be related to the KNITRO package.
If so, please submit your issue to the appropriate package.

**Comment by yeesian** [comment]
The most natural place to post this issue will be in the JuMP package. Fixes there will be [gladly accepted](https://github.com/JuliaOpt/JuMP.jl/issues/849#issuecomment-246275384).
