### ISSUE TITLE
error using a different Options file

### ISSUE THREAD

**Issue by rt5592** [JuliaOpt/KNITRO.jl#79]
Hi
I have a second options file in the same directory (in 'examples' folder) called 'knitro1.opt'.

when I try to call it using:
`loadOptionsFile(kp, joinpath(dirname(@__FILE__),"knitro1.opt"))`

I get an error loading parameters. 

but when I just load the original options file it works:
`loadOptionsFile(kp, joinpath(dirname(@__FILE__),"knitro.opt"))`

I am not sure what's causing the error. 

Thanks!

**Comment by sylvainmouret** [comment]
Hi,

I have tried this with v0.3.1 but I could not reproduce the error.
Can you try again with the latest release (v0.3.1) and also share your new options files with us?
