### ISSUE TITLE
Compatibility with Julia 1.0

### ISSUE THREAD

**Issue by sylvainmouret** [JuliaOpt/KNITRO.jl#86]
It seems Knitro is not yet compatible with Julia 1.0.
I don't know if this is just a requirement that needs updating or if more work is involved.
Does anyone know?

**Comment by blegat** [comment]
Checking the history the last commit is yours in March 13 : https://github.com/JuliaOpt/KNITRO.jl/commits/master so I would guess the package does not support Julia v1.0 yet.

**Comment by sylvainmouret** [comment]
Sure, the requirement says mentions Julia 0.6, but previously, it meant Julia 0.6 and earlier versions.
I guess it it is not sufficient to allow its use with Julia 1.0 (probably due to the change of major version).
That said, we can update the requirement file, but will it be sufficient?
I can try when I find the time, but if anyone has the answer to this question, I'd be glad to hear about it.

**Comment by blegat** [comment]
`Julia 0.6` in the REQUIRE file means that it requires Julia v0.6 or later so Julia v1.0 is not excluded. No change in the REQUIRE file is needed.

**Comment by mlubin** [comment]
More work is involved than updating REQUIRE. Julia 1.0 has tons of breaking changes, and I haven't seen any case where zero changes were needed to get Julia-0.6-compatible code running. That said, the process is not too difficult. If the test coverage is sufficiently good, you can run the package's tests under Julia 0.7 and fix all deprecation warnings. After it runs without deprecation warnings on Julia 0.7, then test it on Julia 1.0.

**Comment by sylvainmouret** [comment]
This issue has been fixed with the latest PR.
We'll create a new release to make it available to everyone.
