### ISSUE TITLE
Pkg.test fail

### ISSUE THREAD

**Issue by rtriolo22** [JuliaOpt/KNITRO.jl#95]
I am getting an error when running `Pkg.test("KNITRO")`

`ERROR: LoadError: LoadError: LoadError: UndefVarError: libknitro not defined`

I have installed Artelys Knitro (and I have successfully run with R and Python). 
I have updated my environment variable and verified that this is accessible in julia:
`julia> ENV["DYLD_LIBRARY_PATH"]`
`"/Applications/knitro-11.1.0-z-MacOS-Intel17-64/lib"`

As mentioned, I have run successfully in Python which I believe uses the same environment variable, so that should be correct.

In my `knitro-11.1.0-z-MacOS-Intel17-64/lib` folder I have the following files:
`libifcore.dylib		libimf.dylib		libknitro.a		libknitro.dylib.11.1	libknitro1110.dylib
libifcoremt.dylib	libintlc.dylib		libknitro.dylib		libknitro.dylib.11.1.0	libsvml.dylib
libifport.dylib		libiomp5.dylib		libknitro.dylib.11	libknitro1110.a`

Julia version: 1.0.2
MacOSX High Sierra: 10.13.6
Knitro version: 11.1.0

Any help would be greatly appreciated.

Thank you,
Ryan

**Comment by sylvainmouret** [comment]
Hi Ryan,
This has been fixed with PR #96 and released under v0.5.2.
Apparently, the interface has never been tested under macOS...
Can you checked that the problem is fixed and close the issue?

**Comment by rtriolo22** [comment]
Thank you Sylvain, 

This did fix the issue. Great work, much appreciated!

Ryan
